apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-hermetic-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-hermetic-example
    app.kubernetes.io/part-of: go-hermetic-example
  name: go-hermetic-example
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-hermetic-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-hermetic-example
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/go-hermetic-example/go-hermetic-example@sha256:684b6856e34b8872a24ed6623ff901fcbcdadc31e6900df75cdb002544e73ae5
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
