apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-hermetic-example-xo4b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-hermetic-example-xo4b
    app.kubernetes.io/part-of: go-hermetic-example
  name: go-hermetic-example-xo4b
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-hermetic-example-xo4b
status:
  loadBalancer: {}
