apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-hermetic-example
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/go-hermetic-example/go-hermetic-example@sha256:f9d9d3905f0e48736eed280a2af359858742a08111cd5758d32479dba8d05953
        name: my-go
        resources: {}
status: {}
